# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: automationservice.proto

require 'google/protobuf'

require 'automation'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Automationservice
end
