# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: automationservice.proto for package 'automationservice'

require 'grpc'
require 'automationservice'

module Automationservice
  module Automation

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'automationservice.Automation'

      rpc :EnqueueClusterOperation, EnqueueClusterOperationRequest, EnqueueClusterOperationResponse
      rpc :GetClusterOperationDetails, GetClusterOperationDetailsRequest, GetClusterOperationDetailsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
