# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: binlogservice.proto

require 'google/protobuf'

require 'binlogdata'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Vitess
  module Binlogservice
  end
end
