# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logutil.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "vitess.logutil.Time" do
    optional :seconds, :int64, 1
    optional :nanoseconds, :int32, 2
  end
  add_message "vitess.logutil.Event" do
    optional :time, :message, 1, "vitess.logutil.Time"
    optional :level, :enum, 2, "vitess.logutil.Level"
    optional :file, :string, 3
    optional :line, :int64, 4
    optional :value, :string, 5
  end
  add_enum "vitess.logutil.Level" do
    value :INFO, 0
    value :WARNING, 1
    value :ERROR, 2
    value :CONSOLE, 3
  end
end

module Vitess
  module Logutil
    Time = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.logutil.Time").msgclass
    Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.logutil.Event").msgclass
    Level = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.logutil.Level").enummodule
  end
end
