# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mysqlctl.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "mysqlctl.StartRequest" do
  end
  add_message "mysqlctl.StartResponse" do
  end
  add_message "mysqlctl.ShutdownRequest" do
    optional :wait_for_mysqld, :bool, 1
  end
  add_message "mysqlctl.ShutdownResponse" do
  end
  add_message "mysqlctl.RunMysqlUpgradeRequest" do
  end
  add_message "mysqlctl.RunMysqlUpgradeResponse" do
  end
end

module Mysqlctl
  StartRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("mysqlctl.StartRequest").msgclass
  StartResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("mysqlctl.StartResponse").msgclass
  ShutdownRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("mysqlctl.ShutdownRequest").msgclass
  ShutdownResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("mysqlctl.ShutdownResponse").msgclass
  RunMysqlUpgradeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("mysqlctl.RunMysqlUpgradeRequest").msgclass
  RunMysqlUpgradeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("mysqlctl.RunMysqlUpgradeResponse").msgclass
end
