# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mysqlctl.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "vitess.mysqlctl.StartRequest" do
  end
  add_message "vitess.mysqlctl.StartResponse" do
  end
  add_message "vitess.mysqlctl.ShutdownRequest" do
    optional :wait_for_mysqld, :bool, 1
  end
  add_message "vitess.mysqlctl.ShutdownResponse" do
  end
  add_message "vitess.mysqlctl.RunMysqlUpgradeRequest" do
  end
  add_message "vitess.mysqlctl.RunMysqlUpgradeResponse" do
  end
end

module Vitess
  module Mysqlctl
    StartRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.mysqlctl.StartRequest").msgclass
    StartResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.mysqlctl.StartResponse").msgclass
    ShutdownRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.mysqlctl.ShutdownRequest").msgclass
    ShutdownResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.mysqlctl.ShutdownResponse").msgclass
    RunMysqlUpgradeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.mysqlctl.RunMysqlUpgradeRequest").msgclass
    RunMysqlUpgradeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.mysqlctl.RunMysqlUpgradeResponse").msgclass
  end
end
