# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mysqlctl.proto for package 'vitess.mysqlctl'

require 'grpc'
require 'mysqlctl'

module Vitess
  module Mysqlctl
    module MysqlCtl

      # TODO: add proto service documentation here
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'vitess.mysqlctl.MysqlCtl'

        rpc :Start, StartRequest, StartResponse
        rpc :Shutdown, ShutdownRequest, ShutdownResponse
        rpc :RunMysqlUpgrade, RunMysqlUpgradeRequest, RunMysqlUpgradeResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
