# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queryservice.proto

require 'google/protobuf'

require 'query'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Vitess
  module Queryservice
  end
end
