# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replicationdata.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "replicationdata.Status" do
    optional :position, :string, 1
    optional :slave_io_running, :bool, 2
    optional :slave_sql_running, :bool, 3
    optional :seconds_behind_master, :uint32, 4
    optional :master_host, :string, 5
    optional :master_port, :int32, 6
    optional :master_connect_retry, :int32, 7
  end
end

module Replicationdata
  Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("replicationdata.Status").msgclass
end
