# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tabletmanagerservice.proto for package 'tabletmanagerservice'

require 'grpc'
require 'tabletmanagerservice'

module Tabletmanagerservice
  module TabletManager

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tabletmanagerservice.TabletManager'

      rpc :Ping, PingRequest, PingResponse
      rpc :Sleep, SleepRequest, SleepResponse
      rpc :ExecuteHook, ExecuteHookRequest, ExecuteHookResponse
      rpc :GetSchema, GetSchemaRequest, GetSchemaResponse
      rpc :GetPermissions, GetPermissionsRequest, GetPermissionsResponse
      rpc :SetReadOnly, SetReadOnlyRequest, SetReadOnlyResponse
      rpc :SetReadWrite, SetReadWriteRequest, SetReadWriteResponse
      rpc :ChangeType, ChangeTypeRequest, ChangeTypeResponse
      rpc :RefreshState, RefreshStateRequest, RefreshStateResponse
      rpc :RunHealthCheck, RunHealthCheckRequest, RunHealthCheckResponse
      rpc :ReloadSchema, ReloadSchemaRequest, ReloadSchemaResponse
      rpc :PreflightSchema, PreflightSchemaRequest, PreflightSchemaResponse
      rpc :ApplySchema, ApplySchemaRequest, ApplySchemaResponse
      rpc :ExecuteFetchAsDba, ExecuteFetchAsDbaRequest, ExecuteFetchAsDbaResponse
      rpc :ExecuteFetchAsApp, ExecuteFetchAsAppRequest, ExecuteFetchAsAppResponse
      rpc :SlaveStatus, SlaveStatusRequest, SlaveStatusResponse
      rpc :MasterPosition, MasterPositionRequest, MasterPositionResponse
      rpc :StopSlave, StopSlaveRequest, StopSlaveResponse
      rpc :StopSlaveMinimum, StopSlaveMinimumRequest, StopSlaveMinimumResponse
      rpc :StartSlave, StartSlaveRequest, StartSlaveResponse
      rpc :TabletExternallyReparented, TabletExternallyReparentedRequest, TabletExternallyReparentedResponse
      rpc :TabletExternallyElected, TabletExternallyElectedRequest, TabletExternallyElectedResponse
      rpc :GetSlaves, GetSlavesRequest, GetSlavesResponse
      rpc :WaitBlpPosition, WaitBlpPositionRequest, WaitBlpPositionResponse
      rpc :StopBlp, StopBlpRequest, StopBlpResponse
      rpc :StartBlp, StartBlpRequest, StartBlpResponse
      rpc :RunBlpUntil, RunBlpUntilRequest, RunBlpUntilResponse
      rpc :ResetReplication, ResetReplicationRequest, ResetReplicationResponse
      rpc :InitMaster, InitMasterRequest, InitMasterResponse
      rpc :PopulateReparentJournal, PopulateReparentJournalRequest, PopulateReparentJournalResponse
      rpc :InitSlave, InitSlaveRequest, InitSlaveResponse
      rpc :DemoteMaster, DemoteMasterRequest, DemoteMasterResponse
      rpc :PromoteSlaveWhenCaughtUp, PromoteSlaveWhenCaughtUpRequest, PromoteSlaveWhenCaughtUpResponse
      rpc :SlaveWasPromoted, SlaveWasPromotedRequest, SlaveWasPromotedResponse
      rpc :SetMaster, SetMasterRequest, SetMasterResponse
      rpc :SlaveWasRestarted, SlaveWasRestartedRequest, SlaveWasRestartedResponse
      rpc :StopReplicationAndGetStatus, StopReplicationAndGetStatusRequest, StopReplicationAndGetStatusResponse
      rpc :PromoteSlave, PromoteSlaveRequest, PromoteSlaveResponse
      rpc :Backup, BackupRequest, stream(BackupResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
