# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tabletmanagerservice.proto

require 'google/protobuf'

require 'tabletmanagerdata'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Tabletmanagerservice
end
