# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tabletmanagerdata.proto

require 'google/protobuf'

require 'query'
require 'topodata'
require 'replicationdata'
require 'logutil'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "vitess.tabletmanagerdata.TableDefinition" do
    optional :name, :string, 1
    optional :schema, :string, 2
    repeated :columns, :string, 3
    repeated :primary_key_columns, :string, 4
    optional :type, :string, 5
    optional :data_length, :uint64, 6
    optional :row_count, :uint64, 7
  end
  add_message "vitess.tabletmanagerdata.SchemaDefinition" do
    optional :database_schema, :string, 1
    repeated :table_definitions, :message, 2, "vitess.tabletmanagerdata.TableDefinition"
    optional :version, :string, 3
  end
  add_message "vitess.tabletmanagerdata.UserPermission" do
    optional :host, :string, 1
    optional :user, :string, 2
    optional :password_checksum, :uint64, 3
    map :privileges, :string, :string, 4
  end
  add_message "vitess.tabletmanagerdata.DbPermission" do
    optional :host, :string, 1
    optional :db, :string, 2
    optional :user, :string, 3
    map :privileges, :string, :string, 4
  end
  add_message "vitess.tabletmanagerdata.Permissions" do
    repeated :user_permissions, :message, 1, "vitess.tabletmanagerdata.UserPermission"
    repeated :db_permissions, :message, 2, "vitess.tabletmanagerdata.DbPermission"
  end
  add_message "vitess.tabletmanagerdata.BlpPosition" do
    optional :uid, :uint32, 1
    optional :position, :string, 2
  end
  add_message "vitess.tabletmanagerdata.PingRequest" do
    optional :payload, :string, 1
  end
  add_message "vitess.tabletmanagerdata.PingResponse" do
    optional :payload, :string, 1
  end
  add_message "vitess.tabletmanagerdata.SleepRequest" do
    optional :duration, :int64, 1
  end
  add_message "vitess.tabletmanagerdata.SleepResponse" do
  end
  add_message "vitess.tabletmanagerdata.ExecuteHookRequest" do
    optional :name, :string, 1
    repeated :parameters, :string, 2
    map :extra_env, :string, :string, 3
  end
  add_message "vitess.tabletmanagerdata.ExecuteHookResponse" do
    optional :exit_status, :int64, 1
    optional :stdout, :string, 2
    optional :stderr, :string, 3
  end
  add_message "vitess.tabletmanagerdata.GetSchemaRequest" do
    repeated :tables, :string, 1
    optional :include_views, :bool, 2
    repeated :exclude_tables, :string, 3
  end
  add_message "vitess.tabletmanagerdata.GetSchemaResponse" do
    optional :schema_definition, :message, 1, "vitess.tabletmanagerdata.SchemaDefinition"
  end
  add_message "vitess.tabletmanagerdata.GetPermissionsRequest" do
  end
  add_message "vitess.tabletmanagerdata.GetPermissionsResponse" do
    optional :permissions, :message, 1, "vitess.tabletmanagerdata.Permissions"
  end
  add_message "vitess.tabletmanagerdata.SetReadOnlyRequest" do
  end
  add_message "vitess.tabletmanagerdata.SetReadOnlyResponse" do
  end
  add_message "vitess.tabletmanagerdata.SetReadWriteRequest" do
  end
  add_message "vitess.tabletmanagerdata.SetReadWriteResponse" do
  end
  add_message "vitess.tabletmanagerdata.ChangeTypeRequest" do
    optional :tablet_type, :enum, 1, "vitess.topodata.TabletType"
  end
  add_message "vitess.tabletmanagerdata.ChangeTypeResponse" do
  end
  add_message "vitess.tabletmanagerdata.RefreshStateRequest" do
  end
  add_message "vitess.tabletmanagerdata.RefreshStateResponse" do
  end
  add_message "vitess.tabletmanagerdata.RunHealthCheckRequest" do
    optional :tablet_type, :enum, 1, "vitess.topodata.TabletType"
  end
  add_message "vitess.tabletmanagerdata.RunHealthCheckResponse" do
  end
  add_message "vitess.tabletmanagerdata.ReloadSchemaRequest" do
  end
  add_message "vitess.tabletmanagerdata.ReloadSchemaResponse" do
  end
  add_message "vitess.tabletmanagerdata.PreflightSchemaRequest" do
    optional :change, :string, 1
  end
  add_message "vitess.tabletmanagerdata.PreflightSchemaResponse" do
    optional :before_schema, :message, 1, "vitess.tabletmanagerdata.SchemaDefinition"
    optional :after_schema, :message, 2, "vitess.tabletmanagerdata.SchemaDefinition"
  end
  add_message "vitess.tabletmanagerdata.ApplySchemaRequest" do
    optional :sql, :string, 1
    optional :force, :bool, 2
    optional :allow_replication, :bool, 3
    optional :before_schema, :message, 4, "vitess.tabletmanagerdata.SchemaDefinition"
    optional :after_schema, :message, 5, "vitess.tabletmanagerdata.SchemaDefinition"
  end
  add_message "vitess.tabletmanagerdata.ApplySchemaResponse" do
    optional :before_schema, :message, 1, "vitess.tabletmanagerdata.SchemaDefinition"
    optional :after_schema, :message, 2, "vitess.tabletmanagerdata.SchemaDefinition"
  end
  add_message "vitess.tabletmanagerdata.ExecuteFetchAsDbaRequest" do
    optional :query, :string, 1
    optional :db_name, :string, 2
    optional :max_rows, :uint64, 3
    optional :want_fields, :bool, 4
    optional :disable_binlogs, :bool, 5
    optional :reload_schema, :bool, 6
  end
  add_message "vitess.tabletmanagerdata.ExecuteFetchAsDbaResponse" do
    optional :result, :message, 1, "vitess.query.QueryResult"
  end
  add_message "vitess.tabletmanagerdata.ExecuteFetchAsAppRequest" do
    optional :query, :string, 1
    optional :max_rows, :uint64, 2
    optional :want_fields, :bool, 3
  end
  add_message "vitess.tabletmanagerdata.ExecuteFetchAsAppResponse" do
    optional :result, :message, 1, "vitess.query.QueryResult"
  end
  add_message "vitess.tabletmanagerdata.SlaveStatusRequest" do
  end
  add_message "vitess.tabletmanagerdata.SlaveStatusResponse" do
    optional :status, :message, 1, "vitess.replicationdata.Status"
  end
  add_message "vitess.tabletmanagerdata.MasterPositionRequest" do
  end
  add_message "vitess.tabletmanagerdata.MasterPositionResponse" do
    optional :position, :string, 1
  end
  add_message "vitess.tabletmanagerdata.StopSlaveRequest" do
  end
  add_message "vitess.tabletmanagerdata.StopSlaveResponse" do
  end
  add_message "vitess.tabletmanagerdata.StopSlaveMinimumRequest" do
    optional :position, :string, 1
    optional :wait_timeout, :int64, 2
  end
  add_message "vitess.tabletmanagerdata.StopSlaveMinimumResponse" do
    optional :position, :string, 1
  end
  add_message "vitess.tabletmanagerdata.StartSlaveRequest" do
  end
  add_message "vitess.tabletmanagerdata.StartSlaveResponse" do
  end
  add_message "vitess.tabletmanagerdata.TabletExternallyReparentedRequest" do
    optional :external_id, :string, 1
  end
  add_message "vitess.tabletmanagerdata.TabletExternallyReparentedResponse" do
  end
  add_message "vitess.tabletmanagerdata.TabletExternallyElectedRequest" do
  end
  add_message "vitess.tabletmanagerdata.TabletExternallyElectedResponse" do
  end
  add_message "vitess.tabletmanagerdata.GetSlavesRequest" do
  end
  add_message "vitess.tabletmanagerdata.GetSlavesResponse" do
    repeated :addrs, :string, 1
  end
  add_message "vitess.tabletmanagerdata.WaitBlpPositionRequest" do
    optional :blp_position, :message, 1, "vitess.tabletmanagerdata.BlpPosition"
    optional :wait_timeout, :int64, 2
  end
  add_message "vitess.tabletmanagerdata.WaitBlpPositionResponse" do
  end
  add_message "vitess.tabletmanagerdata.StopBlpRequest" do
  end
  add_message "vitess.tabletmanagerdata.StopBlpResponse" do
    repeated :blp_positions, :message, 1, "vitess.tabletmanagerdata.BlpPosition"
  end
  add_message "vitess.tabletmanagerdata.StartBlpRequest" do
  end
  add_message "vitess.tabletmanagerdata.StartBlpResponse" do
  end
  add_message "vitess.tabletmanagerdata.RunBlpUntilRequest" do
    repeated :blp_positions, :message, 1, "vitess.tabletmanagerdata.BlpPosition"
    optional :wait_timeout, :int64, 2
  end
  add_message "vitess.tabletmanagerdata.RunBlpUntilResponse" do
    optional :position, :string, 1
  end
  add_message "vitess.tabletmanagerdata.ResetReplicationRequest" do
  end
  add_message "vitess.tabletmanagerdata.ResetReplicationResponse" do
  end
  add_message "vitess.tabletmanagerdata.InitMasterRequest" do
  end
  add_message "vitess.tabletmanagerdata.InitMasterResponse" do
    optional :position, :string, 1
  end
  add_message "vitess.tabletmanagerdata.PopulateReparentJournalRequest" do
    optional :time_created_ns, :int64, 1
    optional :action_name, :string, 2
    optional :master_alias, :message, 3, "vitess.topodata.TabletAlias"
    optional :replication_position, :string, 4
  end
  add_message "vitess.tabletmanagerdata.PopulateReparentJournalResponse" do
  end
  add_message "vitess.tabletmanagerdata.InitSlaveRequest" do
    optional :parent, :message, 1, "vitess.topodata.TabletAlias"
    optional :replication_position, :string, 2
    optional :time_created_ns, :int64, 3
  end
  add_message "vitess.tabletmanagerdata.InitSlaveResponse" do
  end
  add_message "vitess.tabletmanagerdata.DemoteMasterRequest" do
  end
  add_message "vitess.tabletmanagerdata.DemoteMasterResponse" do
    optional :position, :string, 1
  end
  add_message "vitess.tabletmanagerdata.PromoteSlaveWhenCaughtUpRequest" do
    optional :position, :string, 1
  end
  add_message "vitess.tabletmanagerdata.PromoteSlaveWhenCaughtUpResponse" do
    optional :position, :string, 1
  end
  add_message "vitess.tabletmanagerdata.SlaveWasPromotedRequest" do
  end
  add_message "vitess.tabletmanagerdata.SlaveWasPromotedResponse" do
  end
  add_message "vitess.tabletmanagerdata.SetMasterRequest" do
    optional :parent, :message, 1, "vitess.topodata.TabletAlias"
    optional :time_created_ns, :int64, 2
    optional :force_start_slave, :bool, 3
  end
  add_message "vitess.tabletmanagerdata.SetMasterResponse" do
  end
  add_message "vitess.tabletmanagerdata.SlaveWasRestartedRequest" do
    optional :parent, :message, 1, "vitess.topodata.TabletAlias"
  end
  add_message "vitess.tabletmanagerdata.SlaveWasRestartedResponse" do
  end
  add_message "vitess.tabletmanagerdata.StopReplicationAndGetStatusRequest" do
  end
  add_message "vitess.tabletmanagerdata.StopReplicationAndGetStatusResponse" do
    optional :status, :message, 1, "vitess.replicationdata.Status"
  end
  add_message "vitess.tabletmanagerdata.PromoteSlaveRequest" do
  end
  add_message "vitess.tabletmanagerdata.PromoteSlaveResponse" do
    optional :position, :string, 1
  end
  add_message "vitess.tabletmanagerdata.BackupRequest" do
    optional :concurrency, :int64, 1
  end
  add_message "vitess.tabletmanagerdata.BackupResponse" do
    optional :event, :message, 1, "vitess.logutil.Event"
  end
end

module Vitess
  module Tabletmanagerdata
    TableDefinition = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.TableDefinition").msgclass
    SchemaDefinition = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SchemaDefinition").msgclass
    UserPermission = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.UserPermission").msgclass
    DbPermission = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.DbPermission").msgclass
    Permissions = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.Permissions").msgclass
    BlpPosition = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.BlpPosition").msgclass
    PingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PingRequest").msgclass
    PingResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PingResponse").msgclass
    SleepRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SleepRequest").msgclass
    SleepResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SleepResponse").msgclass
    ExecuteHookRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ExecuteHookRequest").msgclass
    ExecuteHookResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ExecuteHookResponse").msgclass
    GetSchemaRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.GetSchemaRequest").msgclass
    GetSchemaResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.GetSchemaResponse").msgclass
    GetPermissionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.GetPermissionsRequest").msgclass
    GetPermissionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.GetPermissionsResponse").msgclass
    SetReadOnlyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SetReadOnlyRequest").msgclass
    SetReadOnlyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SetReadOnlyResponse").msgclass
    SetReadWriteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SetReadWriteRequest").msgclass
    SetReadWriteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SetReadWriteResponse").msgclass
    ChangeTypeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ChangeTypeRequest").msgclass
    ChangeTypeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ChangeTypeResponse").msgclass
    RefreshStateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.RefreshStateRequest").msgclass
    RefreshStateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.RefreshStateResponse").msgclass
    RunHealthCheckRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.RunHealthCheckRequest").msgclass
    RunHealthCheckResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.RunHealthCheckResponse").msgclass
    ReloadSchemaRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ReloadSchemaRequest").msgclass
    ReloadSchemaResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ReloadSchemaResponse").msgclass
    PreflightSchemaRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PreflightSchemaRequest").msgclass
    PreflightSchemaResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PreflightSchemaResponse").msgclass
    ApplySchemaRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ApplySchemaRequest").msgclass
    ApplySchemaResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ApplySchemaResponse").msgclass
    ExecuteFetchAsDbaRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ExecuteFetchAsDbaRequest").msgclass
    ExecuteFetchAsDbaResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ExecuteFetchAsDbaResponse").msgclass
    ExecuteFetchAsAppRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ExecuteFetchAsAppRequest").msgclass
    ExecuteFetchAsAppResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ExecuteFetchAsAppResponse").msgclass
    SlaveStatusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SlaveStatusRequest").msgclass
    SlaveStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SlaveStatusResponse").msgclass
    MasterPositionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.MasterPositionRequest").msgclass
    MasterPositionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.MasterPositionResponse").msgclass
    StopSlaveRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StopSlaveRequest").msgclass
    StopSlaveResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StopSlaveResponse").msgclass
    StopSlaveMinimumRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StopSlaveMinimumRequest").msgclass
    StopSlaveMinimumResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StopSlaveMinimumResponse").msgclass
    StartSlaveRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StartSlaveRequest").msgclass
    StartSlaveResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StartSlaveResponse").msgclass
    TabletExternallyReparentedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.TabletExternallyReparentedRequest").msgclass
    TabletExternallyReparentedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.TabletExternallyReparentedResponse").msgclass
    TabletExternallyElectedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.TabletExternallyElectedRequest").msgclass
    TabletExternallyElectedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.TabletExternallyElectedResponse").msgclass
    GetSlavesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.GetSlavesRequest").msgclass
    GetSlavesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.GetSlavesResponse").msgclass
    WaitBlpPositionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.WaitBlpPositionRequest").msgclass
    WaitBlpPositionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.WaitBlpPositionResponse").msgclass
    StopBlpRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StopBlpRequest").msgclass
    StopBlpResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StopBlpResponse").msgclass
    StartBlpRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StartBlpRequest").msgclass
    StartBlpResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StartBlpResponse").msgclass
    RunBlpUntilRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.RunBlpUntilRequest").msgclass
    RunBlpUntilResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.RunBlpUntilResponse").msgclass
    ResetReplicationRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ResetReplicationRequest").msgclass
    ResetReplicationResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.ResetReplicationResponse").msgclass
    InitMasterRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.InitMasterRequest").msgclass
    InitMasterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.InitMasterResponse").msgclass
    PopulateReparentJournalRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PopulateReparentJournalRequest").msgclass
    PopulateReparentJournalResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PopulateReparentJournalResponse").msgclass
    InitSlaveRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.InitSlaveRequest").msgclass
    InitSlaveResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.InitSlaveResponse").msgclass
    DemoteMasterRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.DemoteMasterRequest").msgclass
    DemoteMasterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.DemoteMasterResponse").msgclass
    PromoteSlaveWhenCaughtUpRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PromoteSlaveWhenCaughtUpRequest").msgclass
    PromoteSlaveWhenCaughtUpResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PromoteSlaveWhenCaughtUpResponse").msgclass
    SlaveWasPromotedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SlaveWasPromotedRequest").msgclass
    SlaveWasPromotedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SlaveWasPromotedResponse").msgclass
    SetMasterRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SetMasterRequest").msgclass
    SetMasterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SetMasterResponse").msgclass
    SlaveWasRestartedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SlaveWasRestartedRequest").msgclass
    SlaveWasRestartedResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.SlaveWasRestartedResponse").msgclass
    StopReplicationAndGetStatusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StopReplicationAndGetStatusRequest").msgclass
    StopReplicationAndGetStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.StopReplicationAndGetStatusResponse").msgclass
    PromoteSlaveRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PromoteSlaveRequest").msgclass
    PromoteSlaveResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.PromoteSlaveResponse").msgclass
    BackupRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.BackupRequest").msgclass
    BackupResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.tabletmanagerdata.BackupResponse").msgclass
  end
end
