# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topodata.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "vitess.topodata.KeyRange" do
    optional :start, :bytes, 1
    optional :end, :bytes, 2
  end
  add_message "vitess.topodata.TabletAlias" do
    optional :cell, :string, 1
    optional :uid, :uint32, 2
  end
  add_message "vitess.topodata.Tablet" do
    optional :alias, :message, 1, "vitess.topodata.TabletAlias"
    optional :hostname, :string, 2
    optional :ip, :string, 3
    map :port_map, :string, :int32, 4
    optional :keyspace, :string, 5
    optional :shard, :string, 6
    optional :key_range, :message, 7, "vitess.topodata.KeyRange"
    optional :type, :enum, 8, "vitess.topodata.TabletType"
    optional :db_name_override, :string, 9
    map :tags, :string, :string, 10
    map :health_map, :string, :string, 11
  end
  add_message "vitess.topodata.Shard" do
    optional :master_alias, :message, 1, "vitess.topodata.TabletAlias"
    optional :key_range, :message, 2, "vitess.topodata.KeyRange"
    repeated :served_types, :message, 3, "vitess.topodata.Shard.ServedType"
    repeated :source_shards, :message, 4, "vitess.topodata.Shard.SourceShard"
    repeated :cells, :string, 5
    repeated :tablet_controls, :message, 6, "vitess.topodata.Shard.TabletControl"
  end
  add_message "vitess.topodata.Shard.ServedType" do
    optional :tablet_type, :enum, 1, "vitess.topodata.TabletType"
    repeated :cells, :string, 2
  end
  add_message "vitess.topodata.Shard.SourceShard" do
    optional :uid, :uint32, 1
    optional :keyspace, :string, 2
    optional :shard, :string, 3
    optional :key_range, :message, 4, "vitess.topodata.KeyRange"
    repeated :tables, :string, 5
  end
  add_message "vitess.topodata.Shard.TabletControl" do
    optional :tablet_type, :enum, 1, "vitess.topodata.TabletType"
    repeated :cells, :string, 2
    optional :disable_query_service, :bool, 3
    repeated :blacklisted_tables, :string, 4
  end
  add_message "vitess.topodata.Keyspace" do
    optional :sharding_column_name, :string, 1
    optional :sharding_column_type, :enum, 2, "vitess.topodata.KeyspaceIdType"
    optional :split_shard_count, :int32, 3
    repeated :served_froms, :message, 4, "vitess.topodata.Keyspace.ServedFrom"
  end
  add_message "vitess.topodata.Keyspace.ServedFrom" do
    optional :tablet_type, :enum, 1, "vitess.topodata.TabletType"
    repeated :cells, :string, 2
    optional :keyspace, :string, 3
  end
  add_message "vitess.topodata.ShardReplication" do
    repeated :nodes, :message, 1, "vitess.topodata.ShardReplication.Node"
  end
  add_message "vitess.topodata.ShardReplication.Node" do
    optional :tablet_alias, :message, 1, "vitess.topodata.TabletAlias"
  end
  add_message "vitess.topodata.EndPoint" do
    optional :uid, :uint32, 1
    optional :host, :string, 2
    map :port_map, :string, :int32, 3
    map :health_map, :string, :string, 4
  end
  add_message "vitess.topodata.EndPoints" do
    repeated :entries, :message, 1, "vitess.topodata.EndPoint"
  end
  add_message "vitess.topodata.SrvShard" do
    optional :name, :string, 1
    optional :key_range, :message, 2, "vitess.topodata.KeyRange"
    optional :master_cell, :string, 3
  end
  add_message "vitess.topodata.ShardReference" do
    optional :name, :string, 1
    optional :key_range, :message, 2, "vitess.topodata.KeyRange"
  end
  add_message "vitess.topodata.SrvKeyspace" do
    repeated :partitions, :message, 1, "vitess.topodata.SrvKeyspace.KeyspacePartition"
    optional :sharding_column_name, :string, 2
    optional :sharding_column_type, :enum, 3, "vitess.topodata.KeyspaceIdType"
    repeated :served_from, :message, 4, "vitess.topodata.SrvKeyspace.ServedFrom"
    optional :split_shard_count, :int32, 5
  end
  add_message "vitess.topodata.SrvKeyspace.KeyspacePartition" do
    optional :served_type, :enum, 1, "vitess.topodata.TabletType"
    repeated :shard_references, :message, 2, "vitess.topodata.ShardReference"
  end
  add_message "vitess.topodata.SrvKeyspace.ServedFrom" do
    optional :tablet_type, :enum, 1, "vitess.topodata.TabletType"
    optional :keyspace, :string, 2
  end
  add_enum "vitess.topodata.KeyspaceIdType" do
    value :UNSET, 0
    value :UINT64, 1
    value :BYTES, 2
  end
  add_enum "vitess.topodata.TabletType" do
    value :UNKNOWN, 0
    value :MASTER, 1
    value :REPLICA, 2
    value :RDONLY, 3
    value :BATCH, 3
    value :SPARE, 4
    value :EXPERIMENTAL, 5
    value :BACKUP, 6
    value :RESTORE, 7
    value :WORKER, 8
  end
end

module Vitess
  module Topodata
    KeyRange = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.KeyRange").msgclass
    TabletAlias = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.TabletAlias").msgclass
    Tablet = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.Tablet").msgclass
    Shard = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.Shard").msgclass
    Shard::ServedType = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.Shard.ServedType").msgclass
    Shard::SourceShard = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.Shard.SourceShard").msgclass
    Shard::TabletControl = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.Shard.TabletControl").msgclass
    Keyspace = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.Keyspace").msgclass
    Keyspace::ServedFrom = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.Keyspace.ServedFrom").msgclass
    ShardReplication = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.ShardReplication").msgclass
    ShardReplication::Node = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.ShardReplication.Node").msgclass
    EndPoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.EndPoint").msgclass
    EndPoints = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.EndPoints").msgclass
    SrvShard = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.SrvShard").msgclass
    ShardReference = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.ShardReference").msgclass
    SrvKeyspace = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.SrvKeyspace").msgclass
    SrvKeyspace::KeyspacePartition = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.SrvKeyspace.KeyspacePartition").msgclass
    SrvKeyspace::ServedFrom = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.SrvKeyspace.ServedFrom").msgclass
    KeyspaceIdType = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.KeyspaceIdType").enummodule
    TabletType = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.topodata.TabletType").enummodule
  end
end
