# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: vtctlservice.proto for package 'vitess.vtctlservice'

require 'grpc'
require 'vtctlservice'

module Vitess
  module Vtctlservice
    module Vtctl

      # TODO: add proto service documentation here
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'vitess.vtctlservice.Vtctl'

        rpc :ExecuteVtctlCommand, ExecuteVtctlCommandRequest, stream(ExecuteVtctlCommandResponse)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
