# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vtctldata.proto

require 'google/protobuf'

require 'logutil'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "vitess.vtctldata.ExecuteVtctlCommandRequest" do
    repeated :args, :string, 1
    optional :action_timeout, :int64, 2
  end
  add_message "vitess.vtctldata.ExecuteVtctlCommandResponse" do
    optional :event, :message, 1, "vitess.logutil.Event"
  end
end

module Vitess
  module Vtctldata
    ExecuteVtctlCommandRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.vtctldata.ExecuteVtctlCommandRequest").msgclass
    ExecuteVtctlCommandResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.vtctldata.ExecuteVtctlCommandResponse").msgclass
  end
end
