# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vtctlservice.proto

require 'google/protobuf'

require 'vtctldata'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Vtctlservice
end
