# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vtgateservice.proto

require 'google/protobuf'

require 'vtgate'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Vtgateservice
end
