# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vtworkerdata.proto

require 'google/protobuf'

require 'logutil'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "vtworkerdata.ExecuteVtworkerCommandRequest" do
    repeated :args, :string, 1
  end
  add_message "vtworkerdata.ExecuteVtworkerCommandResponse" do
    optional :event, :message, 1, "logutil.Event"
  end
end

module Vtworkerdata
  ExecuteVtworkerCommandRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vtworkerdata.ExecuteVtworkerCommandRequest").msgclass
  ExecuteVtworkerCommandResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vtworkerdata.ExecuteVtworkerCommandResponse").msgclass
end
