# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vtworkerdata.proto

require 'google/protobuf'

require 'logutil'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "vitess.vtworkerdata.ExecuteVtworkerCommandRequest" do
    repeated :args, :string, 1
  end
  add_message "vitess.vtworkerdata.ExecuteVtworkerCommandResponse" do
    optional :event, :message, 1, "vitess.logutil.Event"
  end
end

module Vitess
  module Vtworkerdata
    ExecuteVtworkerCommandRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.vtworkerdata.ExecuteVtworkerCommandRequest").msgclass
    ExecuteVtworkerCommandResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("vitess.vtworkerdata.ExecuteVtworkerCommandResponse").msgclass
  end
end
