# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: vtworkerservice.proto for package 'vitess.vtworkerservice'

require 'grpc'
require 'vtworkerservice'

module Vitess
  module Vtworkerservice
    module Vtworker

      # TODO: add proto service documentation here
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'vitess.vtworkerservice.Vtworker'

        rpc :ExecuteVtworkerCommand, ExecuteVtworkerCommandRequest, stream(ExecuteVtworkerCommandResponse)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
